use_frameworks!

platform :ios, '11.0'

target 'LLSMSCodeViewController_Example' do
  pod 'LLSMSCodeViewController', :path => '../'

  target 'LLSMSCodeViewController_Tests' do
    inherit! :search_paths
    
    pod 'LLSMSCodeViewController', :path => '../'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
