use_frameworks!

platform :ios, '9.0'

target 'LLSMSCodeViewController_Example' do
  pod 'LLSMSCodeViewController', :path => '../'

  target 'LLSMSCodeViewController_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
